# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peter/CCPPPrograms/SDL_TEST

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peter/CCPPPrograms/SDL_TEST

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/CCPPPrograms/SDL_TEST/CMakeFiles /home/peter/CCPPPrograms/SDL_TEST/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/CCPPPrograms/SDL_TEST/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named caster

# Build rule for target.
caster: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 caster
.PHONY : caster

# fast build rule for target.
caster/fast:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/build
.PHONY : caster/fast

caster_math.o: caster_math.cpp.o

.PHONY : caster_math.o

# target to build an object file
caster_math.cpp.o:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/caster_math.cpp.o
.PHONY : caster_math.cpp.o

caster_math.i: caster_math.cpp.i

.PHONY : caster_math.i

# target to preprocess a source file
caster_math.cpp.i:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/caster_math.cpp.i
.PHONY : caster_math.cpp.i

caster_math.s: caster_math.cpp.s

.PHONY : caster_math.s

# target to generate assembly for a file
caster_math.cpp.s:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/caster_math.cpp.s
.PHONY : caster_math.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/main.cpp.s
.PHONY : main.cpp.s

map.o: map.cpp.o

.PHONY : map.o

# target to build an object file
map.cpp.o:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/map.cpp.o
.PHONY : map.cpp.o

map.i: map.cpp.i

.PHONY : map.i

# target to preprocess a source file
map.cpp.i:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/map.cpp.i
.PHONY : map.cpp.i

map.s: map.cpp.s

.PHONY : map.s

# target to generate assembly for a file
map.cpp.s:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/map.cpp.s
.PHONY : map.cpp.s

player.o: player.cpp.o

.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i

.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s

.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/player.cpp.s
.PHONY : player.cpp.s

raycaster.o: raycaster.cpp.o

.PHONY : raycaster.o

# target to build an object file
raycaster.cpp.o:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/raycaster.cpp.o
.PHONY : raycaster.cpp.o

raycaster.i: raycaster.cpp.i

.PHONY : raycaster.i

# target to preprocess a source file
raycaster.cpp.i:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/raycaster.cpp.i
.PHONY : raycaster.cpp.i

raycaster.s: raycaster.cpp.s

.PHONY : raycaster.s

# target to generate assembly for a file
raycaster.cpp.s:
	$(MAKE) -f CMakeFiles/caster.dir/build.make CMakeFiles/caster.dir/raycaster.cpp.s
.PHONY : raycaster.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... caster"
	@echo "... caster_math.o"
	@echo "... caster_math.i"
	@echo "... caster_math.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... map.o"
	@echo "... map.i"
	@echo "... map.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... raycaster.o"
	@echo "... raycaster.i"
	@echo "... raycaster.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

